CREATE TABLE MEDICOS(

    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CRM VARCHAR(6) NOT NULL UNIQUE,
    ESPECIALIDADE VARCHAR(100) NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(20),
    BAIRRO VARCHAR(100) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    CEP VARCHAR(9) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    UF CHAR(2) NOT NULL

);