CREATE TABLE PACIENTES(

  ID SERIAL PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  CPF VARCHAR(14) NOT NULL UNIQUE,
  LOGRADOURO VARCHAR(100) NOT NULL,
  BAIRRO VARCHAR(100) NOT NULL,
  CEP VARCHAR(9) NOT NULL,
  COMPLEMENTO VARCHAR(100),
  NUMERO VARCHAR(20),
  UF CHAR(2) NOT NULL,
  CIDADE VARCHAR(100) NOT NULL,
  TELEFONE VARCHAR(20) NOT NULL,
  ATIVO SMALLINT NOT NULL

);